# Generated by Django 6.0 on 2026-01-23 02:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='historicaldespesa',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa'),
        ),
        migrations.AlterField(
            model_name='historicaldespesa',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='historicaldespesa',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa'),
        ),
    ]
