# Generated by Django 6.0 on 2026-01-27 01:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_financeiro', '0002_despesa_pago_historicaldespesa_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/Fatura'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/Fatura'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='historicaldespesa',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/Fatura'),
        ),
        migrations.AlterField(
            model_name='historicaldespesa',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicaldespesa',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='historicalfatura',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Documento/Fatura'),
        ),
        migrations.AlterField(
            model_name='historicalfatura',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicalfatura',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='historicalfatura',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='historicalfatura',
            name='valor_original',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
