# Generated by Django 6.0 on 2026-01-30 01:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('comercial', 'Comercial / Vendas'), ('financeiro', 'Financeiro'), ('operacional', 'Operacional / Técnico'), ('diretoria', 'Diretoria / ADM'), ('outro', 'Outros')], default='outro', max_length=20, verbose_name='Departamento / Função'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MetaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês correspondente')),
                ('valor_meta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='tc_core.vendedor')),
            ],
            options={
                'verbose_name': 'Meta de Venda',
                'verbose_name_plural': 'Metas de Vendas',
                'unique_together': {('vendedor', 'mes_referencia')},
            },
        ),
    ]
