# Generated by Django 6.0 on 2026-01-18 14:44

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('tipo_contrato', models.CharField(choices=[('REC', 'Receita (Cliente)'), ('DESP', 'Despesa (Consumo/Fornecedor)')], default='REC', max_length=5, verbose_name='Tipo de Contrato')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto e Especificações')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mensal')),
                ('dia_vencimento', models.PositiveIntegerField(default=10, verbose_name='Dia de Vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('indice_reajuste', models.CharField(choices=[('IGPM', 'IGP-M'), ('IPCA', 'IPCA'), ('FIXO', 'Sem Reajuste (Fixo)')], default='IPCA', max_length=10, verbose_name='Índice')),
                ('data_proxima_renovacao', models.DateField(blank=True, null=True, verbose_name='Próxima Renovação')),
                ('situacao', models.CharField(choices=[('ELAB', 'Em Elaboração'), ('ASSIN', 'Aguardando Assinatura'), ('ATIVO', 'Ativo'), ('SUSP', 'Suspenso'), ('ENCER', 'Encerrado/Finalizado')], default='ELAB', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContrato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='Número do Contrato')),
                ('tipo_contrato', models.CharField(choices=[('REC', 'Receita (Cliente)'), ('DESP', 'Despesa (Consumo/Fornecedor)')], default='REC', max_length=5, verbose_name='Tipo de Contrato')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto e Especificações')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mensal')),
                ('dia_vencimento', models.PositiveIntegerField(default=10, verbose_name='Dia de Vencimento')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('indice_reajuste', models.CharField(choices=[('IGPM', 'IGP-M'), ('IPCA', 'IPCA'), ('FIXO', 'Sem Reajuste (Fixo)')], default='IPCA', max_length=10, verbose_name='Índice')),
                ('data_proxima_renovacao', models.DateField(blank=True, null=True, verbose_name='Próxima Renovação')),
                ('situacao', models.CharField(choices=[('ELAB', 'Em Elaboração'), ('ASSIN', 'Aguardando Assinatura'), ('ATIVO', 'Ativo'), ('SUSP', 'Suspenso'), ('ENCER', 'Encerrado/Finalizado')], default='ELAB', max_length=10, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Contrato',
                'verbose_name_plural': 'historical Contratos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
