# Generated by Django 6.0 on 2026-02-03 15:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_crm', '0002_metamensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproposta',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Frete (R$)'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor do Frete (R$)'),
        ),
    ]
