# Generated by Django 6.0 on 2026-01-18 14:44

import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacaoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=15, verbose_name='Decisão')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários do Aprovador')),
            ],
            options={
                'verbose_name': 'Aprovação de Requisição',
                'verbose_name_plural': 'Aprovações de Requisição',
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Centro de Custo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAprovacaoRequisicao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=15, verbose_name='Decisão')),
                ('data_decisao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Decisão')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentários do Aprovador')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Aprovação de Requisição',
                'verbose_name_plural': 'historical Aprovações de Requisição',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalItemPedidoCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('quantidade_pedida', models.PositiveIntegerField(default=1, verbose_name='Quantidade Pedida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário Negociado (R$)')),
                ('quantidade_recebida', models.PositiveIntegerField(default=0, verbose_name='Quantidade Recebida Acumulada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Item do Pedido de Compra',
                'verbose_name_plural': 'historical Itens do Pedido de Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPedidoCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Fornecedor'), ('parcial', 'Recebido Parcialmente'), ('total', 'Recebido Totalmente'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status do Pedido')),
                ('data_emissao', models.DateField(blank=True, editable=False, verbose_name='Data de Emissão')),
                ('custo_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo do Frete')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pedido de Compra (PO)',
                'verbose_name_plural': 'historical Pedidos de Compra (POs)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecebimentoItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantidade_recebida', models.PositiveIntegerField(verbose_name='Quantidade Recebida Nesta Transação')),
                ('data_recebimento', models.DateTimeField(blank=True, editable=False, verbose_name='Data/Hora do Recebimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações (Divergências, Qualidade, etc.)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Recebimento de Item',
                'verbose_name_plural': 'historical Recebimentos de Itens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequisicaoCompra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data da Solicitação')),
                ('data_limite', models.DateField(verbose_name='Prazo Desejado')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente Aprovação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('convertida', 'Convertida em Pedido')], default='rascunho', max_length=20, verbose_name='Status da Requisição')),
                ('descricao_geral', models.TextField(verbose_name='Descrição/Motivo Geral da Compra')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Requisição de Compra',
                'verbose_name_plural': 'historical Requisições de Compra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_item', models.CharField(max_length=255, verbose_name='Descrição do Item')),
                ('quantidade_pedida', models.PositiveIntegerField(default=1, verbose_name='Quantidade Pedida')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário Negociado (R$)')),
                ('quantidade_recebida', models.PositiveIntegerField(default=0, verbose_name='Quantidade Recebida Acumulada')),
            ],
            options={
                'verbose_name': 'Item do Pedido de Compra',
                'verbose_name_plural': 'Itens do Pedido de Compra',
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_customizado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Customizado do Item')),
                ('especificacao', models.TextField(verbose_name='Especificação/Detalhes Técnicos')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade Solicitada')),
                ('preco_unitario_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário Estimado (R$)')),
            ],
            options={
                'verbose_name': 'Item da Requisição',
                'verbose_name_plural': 'Itens da Requisição',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Fornecedor'), ('parcial', 'Recebido Parcialmente'), ('total', 'Recebido Totalmente'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20, verbose_name='Status do Pedido')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('custo_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Custo do Frete')),
            ],
            options={
                'verbose_name': 'Pedido de Compra (PO)',
                'verbose_name_plural': 'Pedidos de Compra (POs)',
            },
        ),
        migrations.CreateModel(
            name='RecebimentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.PositiveIntegerField(verbose_name='Quantidade Recebida Nesta Transação')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Recebimento')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações (Divergências, Qualidade, etc.)')),
            ],
            options={
                'verbose_name': 'Recebimento de Item',
                'verbose_name_plural': 'Recebimentos de Itens',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_limite', models.DateField(verbose_name='Prazo Desejado')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente Aprovação'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('convertida', 'Convertida em Pedido')], default='rascunho', max_length=20, verbose_name='Status da Requisição')),
                ('descricao_geral', models.TextField(verbose_name='Descrição/Motivo Geral da Compra')),
            ],
            options={
                'verbose_name': 'Requisição de Compra',
                'verbose_name_plural': 'Requisições de Compra',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
