# Generated by Django 6.0 on 2026-01-18 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tc_compras', '0001_initial'),
        ('tc_financeiro', '0001_initial'),
        ('tc_produtos', '0001_initial'),
        ('tc_servicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacaorequisicao',
            name='aprovador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Designado'),
        ),
        migrations.AddField(
            model_name='historicalaprovacaorequisicao',
            name='aprovador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Designado'),
        ),
        migrations.AddField(
            model_name='historicalaprovacaorequisicao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitempedidocompra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpedidocompra',
            name='fatura_vinculada',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_financeiro.despesa', verbose_name='Despesa (Contas a Pagar)'),
        ),
        migrations.AddField(
            model_name='historicalpedidocompra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_produtos.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalpedidocompra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrecebimentoitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrecebimentoitem',
            name='recebedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Recebimento'),
        ),
        migrations.AddField(
            model_name='historicalrequisicaocompra',
            name='centro_custo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='historicalrequisicaocompra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequisicaocompra',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Área/Usuário Solicitante'),
        ),
        migrations.AddField(
            model_name='historicalrecebimentoitem',
            name='item_pedido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.itempedidocompra', verbose_name='Item do Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='itemrequisicao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tc_produtos.produto', verbose_name='Produto (Catálogo)'),
        ),
        migrations.AddField(
            model_name='itemrequisicao',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tc_servicos.servico', verbose_name='Serviço (Catálogo)'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='requisicao_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_compras.itemrequisicao', verbose_name='Item da Requisição de Origem'),
        ),
        migrations.AddField(
            model_name='historicalitempedidocompra',
            name='requisicao_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.itemrequisicao', verbose_name='Item da Requisição de Origem'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fatura_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_financeiro.despesa', verbose_name='Despesa (Contas a Pagar)'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc_produtos.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='tc_compras.pedidocompra', verbose_name='Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='historicalitempedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.pedidocompra', verbose_name='Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='recebimentoitem',
            name='item_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='tc_compras.itempedidocompra', verbose_name='Item do Pedido de Compra'),
        ),
        migrations.AddField(
            model_name='recebimentoitem',
            name='recebedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Recebimento'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='centro_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc_compras.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='requisicaocompra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Área/Usuário Solicitante'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='requisicao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_compras.requisicaocompra', verbose_name='Requisição de Origem'),
        ),
        migrations.AddField(
            model_name='itemrequisicao',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_requisicao', to='tc_compras.requisicaocompra', verbose_name='Requisição'),
        ),
        migrations.AddField(
            model_name='historicalpedidocompra',
            name='requisicao_origem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.requisicaocompra', verbose_name='Requisição de Origem'),
        ),
        migrations.AddField(
            model_name='historicalaprovacaorequisicao',
            name='requisicao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_compras.requisicaocompra', verbose_name='Requisição de Compra'),
        ),
        migrations.AddField(
            model_name='aprovacaorequisicao',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='tc_compras.requisicaocompra', verbose_name='Requisição de Compra'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedidocompra',
            unique_together={('pedido_compra', 'descricao_item')},
        ),
        migrations.AddConstraint(
            model_name='itemrequisicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('produto__isnull', False), ('servico__isnull', True)), models.Q(('produto__isnull', True), ('servico__isnull', False)), _connector='OR'), name='apenas_um_tipo_de_item_requisicao'),
        ),
        migrations.AlterUniqueTogether(
            name='aprovacaorequisicao',
            unique_together={('requisicao', 'aprovador')},
        ),
    ]
