# Generated by Django 6.0 on 2026-01-18 14:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tc_contratos', '0001_initial'),
        ('tc_crm', '0001_initial'),
        ('tc_produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Operação',
                'verbose_name_plural': 'Categorias de Operações',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Fabricante')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativos',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=100, unique=True, verbose_name='Serial/Service Tag/ID')),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_expiracao_garantia', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos_instalados', to='tc_crm.cliente', verbose_name='Cliente/Conta')),
                ('produto_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos_operacionais', to='tc_produtos.produto', verbose_name='Produto no Catálogo')),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_operacoes.fabricante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc_operacoes.tipoativo')),
            ],
            options={
                'verbose_name': 'Ativo (CMDB)',
                'verbose_name_plural': 'Ativos (CMDB)',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao_incidente', models.TextField()),
                ('prioridade', models.CharField(choices=[('1', 'Crítica / Parada Total'), ('2', 'Alta'), ('3', 'Média / Normal'), ('4', 'Baixa')], default='3', max_length=1)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('ASS', 'Atribuído'), ('PEN', 'Pendente / Aguardando'), ('RES', 'Resolvido'), ('CLO', 'Fechado')], default='NEW', max_length=3)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_interacao', models.DateTimeField(auto_now=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('atendente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('ativo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_operacoes.ativo', verbose_name='Ativo com Problema')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tc_operacoes.categoriaoperacao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='tc_crm.cliente')),
                ('solicitante_contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_crm.contato')),
            ],
            options={
                'verbose_name': 'Chamado / Ticket',
                'verbose_name_plural': 'Chamados / Tickets',
                'ordering': ['prioridade', '-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChamado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, editable=False, max_length=20)),
                ('assunto', models.CharField(max_length=200)),
                ('descricao_incidente', models.TextField()),
                ('prioridade', models.CharField(choices=[('1', 'Crítica / Parada Total'), ('2', 'Alta'), ('3', 'Média / Normal'), ('4', 'Baixa')], default='3', max_length=1)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('ASS', 'Atribuído'), ('PEN', 'Pendente / Aguardando'), ('RES', 'Resolvido'), ('CLO', 'Fechado')], default='NEW', max_length=3)),
                ('data_abertura', models.DateTimeField(blank=True, editable=False)),
                ('data_ultima_interacao', models.DateTimeField(blank=True, editable=False)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atendente_responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ativo_vinculado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_operacoes.ativo', verbose_name='Ativo com Problema')),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_operacoes.categoriaoperacao')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_crm.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante_contato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_crm.contato')),
            ],
            options={
                'verbose_name': 'historical Chamado / Ticket',
                'verbose_name_plural': 'historical Chamados / Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFabricante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome do Fabricante')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fabricante',
                'verbose_name_plural': 'historical Fabricantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrdemServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_os', models.CharField(db_index=True, max_length=20, verbose_name='Nº da OS')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Ordem de Serviço')),
                ('descricao', models.TextField(verbose_name='Escopo do Trabalho')),
                ('status', models.CharField(choices=[('RAS', 'Rascunho'), ('ABE', 'Aberto / Aguardando Atendimento'), ('AND', 'Em Atendimento'), ('AG_CLI', 'Aguardando Cliente'), ('AG_TER', 'Aguardando Peça/Terceiro'), ('CON', 'Concluído'), ('CAN', 'Cancelado')], default='RAS', max_length=30, verbose_name='Status da OS')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_previsao_fim', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento Real')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_crm.cliente')),
                ('contrato_vinculado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_contratos.contrato', verbose_name='Contrato Recorrente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oportunidade_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_crm.oportunidade', verbose_name='Oportunidade de Origem')),
                ('responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Operacional')),
            ],
            options={
                'verbose_name': 'historical Ordem de Serviço',
                'verbose_name_plural': 'historical Ordens de Serviço',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InteracaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('e_nota_interna', models.BooleanField(default=False, help_text='Se marcado, o cliente não visualiza esta interação.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='tc_operacoes.chamado')),
            ],
            options={
                'verbose_name': 'Interação de Chamado',
                'verbose_name_plural': 'Interações de Chamados',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True, verbose_name='Nº da OS')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Ordem de Serviço')),
                ('descricao', models.TextField(verbose_name='Escopo do Trabalho')),
                ('status', models.CharField(choices=[('RAS', 'Rascunho'), ('ABE', 'Aberto / Aguardando Atendimento'), ('AND', 'Em Atendimento'), ('AG_CLI', 'Aguardando Cliente'), ('AG_TER', 'Aguardando Peça/Terceiro'), ('CON', 'Concluído'), ('CAN', 'Cancelado')], default='RAS', max_length=30, verbose_name='Status da OS')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_previsao_fim', models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento Real')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='tc_crm.cliente')),
                ('contrato_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_contratos.contrato', verbose_name='Contrato Recorrente')),
                ('oportunidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_crm.oportunidade', verbose_name='Oportunidade de Origem')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Operacional')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolucaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_solucao', models.TextField()),
                ('data_resolucao', models.DateTimeField(auto_now_add=True)),
                ('tempo_gasto_minutos', models.PositiveIntegerField(default=0)),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solucao', to='tc_operacoes.chamado')),
            ],
            options={
                'verbose_name': 'Solução de Chamado',
                'verbose_name_plural': 'Soluções de Chamados',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAtivo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identificador_unico', models.CharField(db_index=True, max_length=100, verbose_name='Serial/Service Tag/ID')),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_expiracao_garantia', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_crm.cliente', verbose_name='Cliente/Conta')),
                ('fabricante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_operacoes.fabricante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produto_catalogo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_produtos.produto', verbose_name='Produto no Catálogo')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_operacoes.tipoativo')),
            ],
            options={
                'verbose_name': 'historical Ativo (CMDB)',
                'verbose_name_plural': 'historical Ativos (CMDB)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
