# Generated by Django 6.0 on 2026-01-18 14:44

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota Padrão ISS (%)')),
            ],
            options={
                'verbose_name': 'Categoria de Serviço',
                'verbose_name_plural': 'Categorias de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoriaServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota Padrão ISS (%)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categoria de Serviço',
                'verbose_name_plural': 'historical Categorias de Serviços',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
                ('codigo_servico', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código do Serviço')),
                ('descricao_curta', models.TextField(verbose_name='Descrição Curta (para Propostas)')),
                ('tipo_servico', models.CharField(choices=[('recorrente', 'Recorrente (Mensal/Anual)'), ('unico', 'Único (Projeto/Hora)')], default='unico', max_length=20, verbose_name='Tipo de Serviço')),
                ('preco_unitario_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário Padrão (R$)')),
                ('unidade_medida', models.CharField(default='un', help_text='Ex: H (hora), Mês, Un (unidade), Pj (projeto)', max_length=20, verbose_name='Unidade de Medida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tc_servicos.categoriaservico', verbose_name='Categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Serviço',
                'verbose_name_plural': 'historical Serviços',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Serviço')),
                ('codigo_servico', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do Serviço')),
                ('descricao_curta', models.TextField(verbose_name='Descrição Curta (para Propostas)')),
                ('tipo_servico', models.CharField(choices=[('recorrente', 'Recorrente (Mensal/Anual)'), ('unico', 'Único (Projeto/Hora)')], default='unico', max_length=20, verbose_name='Tipo de Serviço')),
                ('preco_unitario_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário Padrão (R$)')),
                ('unidade_medida', models.CharField(default='un', help_text='Ex: H (hora), Mês, Un (unidade), Pj (projeto)', max_length=20, verbose_name='Unidade de Medida')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_servicos.categoriaservico', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
